import pygame

BACK = pygame.image.load("img/back.png")

HUMAN_FIRST = pygame.Rect(280, 400, 60, 84)
HUMAN_SECOND = pygame.Rect(360, 400, 60, 84)
HUMAN_THIRD = pygame.Rect(440, 400, 60, 84)
COMPUTER_FIRST = pygame.Rect(280, 100, 60, 84)
COMPUTER_SECOND = pygame.Rect(360, 100, 60, 84)
COMPUTER_THIRD = pygame.Rect(440, 100, 60, 84)
WIDOW_LEFT = pygame.Rect(320, 250, 60, 84)
WIDOW_RIGHT = pygame.Rect(410, 250, 60, 84)

HUMAN_FIRST_HASH = tuple(HUMAN_FIRST)
HUMAN_SECOND_HASH = tuple(HUMAN_SECOND)
HUMAN_THIRD_HASH = tuple(HUMAN_THIRD)
COMPUTER_FIRST_HASH = tuple(COMPUTER_FIRST)
COMPUTER_SECOND_HASH = tuple(COMPUTER_SECOND)
COMPUTER_THIRD_HASH = tuple(COMPUTER_THIRD)
WIDOW_LEFT_HASH = tuple(WIDOW_LEFT)
WIDOW_RIGHT_HASH = tuple(WIDOW_RIGHT)

PAIRS = {HUMAN_FIRST_HASH: None, HUMAN_SECOND_HASH: None, HUMAN_THIRD_HASH: None, COMPUTER_FIRST_HASH: None,
         COMPUTER_SECOND_HASH: None, COMPUTER_THIRD_HASH: None, WIDOW_LEFT_HASH: None, WIDOW_RIGHT_HASH: None}

RECTS = (HUMAN_FIRST, HUMAN_SECOND, HUMAN_THIRD, COMPUTER_FIRST,
         COMPUTER_SECOND,COMPUTER_THIRD,WIDOW_LEFT, WIDOW_RIGHT)

HUMAN = "HUMAN"
COMPUTER = "COMPUTER"
TURN = HUMAN

WIDOW = None

ALLCARDS = None

TABLEHIT = (False, None)

CHANGEROUND = False
HUMANCHIPS = 3
COMPUTERCHIPS = 3

CARDS = None

HUMAN_PLAYER = None
COMPUTER_PLAYER = None

